name: Dynamic Programming

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: knapsack
      run: make dyn_programming/knap && ./dyn_programming/knap
    - name: subset_sum
      run: make dyn_programming/subset_sum && ./dyn_programming/subset_sum
    - name: fib
      run: make dyn_programming/fib && ./dyn_programming/fib
    
