name: Graph Algorithms

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: djikstra
      run: make graphs/djiktra && ./graphs/djiktra
    
    - name: floyd_warshall
      run: make graphs/fwarshall && ./graphs/fwarshall
    
    - name: bellman_ford
      run: make graphs/bford && ./graphs/bford
    
