name: Graph Algorithms

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: djikstra
      run: make graphs/djikstra && ./graphs/djikstra
    
